dist: xenial
sudo: required
language: minimal
before_install:
  - cd .tests/
  - sudo curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
  - sudo pip install -U bashate
  - sudo snap install yq
  - cd ..
  - export PATH=$PWD/.tests/:$PATH
addons:
  apt:
    update: true
jobs:
  include:
    - stage: validate
      script: 
        - sudo bash ./media-docker.sh -t v_bashate
        - sudo bash ./media-docker.sh -t v_shellcheck
    - stage: test
      script: 
        - sudo bash ./media-docker.sh -t t_unit
        - sudo bash ./media-docker.sh -t t_ports
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4a0a4fbecf6a8e55d891
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
